{% set version = "10.2" %}
{% set git_tag = "v10_2" %}
{% set sha256 = "f54d91821223c71c70f4735a1fb2af39c62efbccdeb9b0060ea1cf9c67647ee3" %}

package:
  name: iverilog
  version: {{ version }}

source:
  fn: {{ git_tag }}.tar.gz
  url: https://github.com/steveicarus/iverilog/archive/{{ git_tag }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  detect_binary_files_with_prefix: True

requirements:
  build:
    - autoconf  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - m2-autoconf  # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]

  host:
    - gperf  # [not win]
    - bison  # [not win]
    - flex  # [not win]
    - readline  # [not win]
    - m2-gperf  # [win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - zlib

test:
  commands:
    - test -f "${PREFIX}/bin/iverilog"  # [unix]
    - test -f "${PREFIX}/bin/iverilog-vpi"  # [unix]
    - test -f "${PREFIX}/bin/vvp"  # [unix]
    - test -f "${PREFIX}/lib/libveriuser.a"  # [unix]
    - test -f "${PREFIX}/lib/libvpi.a"  # [unix]
    - test -f "${PREFIX}/lib/ivl/ivl"  # [unix]
    - test -f "${PREFIX}/lib/ivl/ivlpp"  # [unix]
    - test -f "${PREFIX}/lib/ivl/vhdlpp"  # [unix]

about:
  home: http://iverilog.icarus.com/home
  license: GPL-2.0
  summary: 'Icarus Verilog is intended to compile ALL of the Verilog HDL as described in the IEEE-1364 standard.'

extra:
  recipe-maintainers:
    - tfors
    - carlodri
