# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "p8jkF0DF/wmj3gd6cceqB3W102fyS9+hMkPBpUih/IyqmyfX6w1xdW1O81A4L4FZwmcJOmD+iolQoAQ06V6/cI93sqW2uR4Mbfe/Mac8sku65E7JEXSIp/tFBJRiXTXZjGTE66sogp70uWJN4Wxixo7VwlOv/rQLuixyD7kS1DVbRPleyIm6KbX+G2RDJnaHZ0OjXE7ci7qbtQa+YDXAOgL5pbawx/TXQQf4MnqFEOOiziIx1+auaO+6A96X34UNcdg5pLKEpjvLQ/eB6lj26KbFvk3L2HH4iDck2x/KsjKSV3ep/eS+3dzNQp4+gMAZy81nPEpVm/qPtwxwlfRI9zy+LrMTN+m9LZGj87HmWymeZ1tdu/gHzchRMvoqAmsgc+gfL0LEZLrbHcHJJ/8ykfG8kVZ9H4vK38t0b5XFQpwarWTdEA/XiKUpuAhOuddf2l13k+fyP1L19tYghxAyBPBY1v+dJveSSvNXUPU/GyakjEOPL/fpCiTm7LwOUiCzyRuhfVKZdDwwCjDXV5r2sncDI9LGsQFoTiSMyIBRmM3MLMvSV4GkO/sD4wzaAvbNeBTaxky3DZUaS3cYoXufHzVR79MGdmUrMvPCky0kqu1YQsUF4OKojZROT/5/OvEq+EchAnIHkhjyohIDSFFntgwzyxsqIwRX18MErv7QwDI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
