travis:
  secure:
    BINSTAR_TOKEN: Cxvpj7GbCq14r+L2B0CcTq1+jCrJD7s1OOI7UymyGbDIjqKWHaliYNCU0AVwrPv9Ef5bUCezB6ZFnzxfI1eif2GWKOfbXJRQB3nb1hrvodcnq43QuQX2mk9K3wpyE9o/gwKyDwkFoWU3b5+1l7Alyz3sBn2PR8PnLiLtAHWMnpEfhMG+MwGNVX5JjC5RDfTWoM5WmNGroUOyQius1DvIrRl/B4HtnUX2jYRkdVqPtjpEZEiOcA78Lb9DWsQjYaacHIzdK29A5Hz+E59czSCXOW/FQHDjUrAb3l1HCo0ZsZmtNg70byGrO++DhC93lRnMS+/qMLrupPiKkWpafMHrLi8tNXzEjUBD1pvhQlcZQjmyiLurSAz02aOoaNGLeM0UN2vAvpAKj81zct31Mrxy5I01+Vb+gPBwOrZr+2j3K9/mSyK7i0Ppbc5e6umjd0dDpbkh0i8nP/Nbcfg3xk2Dgx/tGBSJDc2TDrn5VRo5lEVOR9cBgKfgHwzlHBEr4anhpNDscsgul2oN4A7OEa1M0LSmwv2vqfFUC53Iq/+cj3Yf9p1hTC0M6MteQzB1OMlvGnhux5KFGzULuu2bVLWQ8CplRrzdDgCYjEaiGd+ttr4KwjW5+2d6O1PnAargU2dyIICOBYSllzNcoab+DNgwV1PyN6d1evpV5d34uZpcx+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
